version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=your-secret-key-here
    volumes:
      - ./instance:/app/instance:rw
    restart: always